# Generated by Django 5.2.5 on 2025-11-26 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทร')),
                ('default_address', models.TextField(blank=True, verbose_name='ที่อยู่เริ่มต้น')),
                ('role', models.CharField(choices=[('customer', 'ผู้ใช้งาน'), ('driver', 'คนขับรถ')], default='customer', max_length=20, verbose_name='บทบาท')),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics', verbose_name='รูปโปรไฟล์')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='วันเกิด')),
                ('address_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ละติจูด')),
                ('address_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ลองจิจูด')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
