# Generated by Django 5.2.5 on 2025-11-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('is_active', models.BooleanField(default=True, verbose_name='แสดงสินค้า')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพสินค้า')),
            ],
        ),
    ]
