# Generated by Django 5.2.5 on 2025-11-26 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่จัดส่ง')),
                ('time_slot', models.CharField(choices=[('morning', '09:00 - 12:00 (เช้า)'), ('afternoon', '13:00 - 16:00 (บ่าย)'), ('evening', '17:00 - 20:00 (เย็น/ค่ำ)')], default='morning', max_length=20, verbose_name='ช่วงเวลา')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='รับได้สูงสุด (ออเดอร์)')),
                ('status', models.CharField(choices=[('open', 'เปิดรับ'), ('locked', 'ปิดรับ/จัดของ'), ('closed', 'ปิดรอบ'), ('completed', 'เสร็จสิ้น')], default='open', max_length=20)),
                ('depot_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('depot_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds', to='accounts.profile', verbose_name='คนขับ')),
            ],
            options={
                'verbose_name': 'รอบจัดส่ง',
                'verbose_name_plural': 'รอบจัดส่ง',
                'ordering': ['date', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'รอชำระ/ใหม่'), ('processing', 'กำลังเตรียมของ'), ('out_for_delivery', 'กำลังจัดส่ง'), ('delivered', 'ส่งสำเร็จ'), ('cancelled', 'ยกเลิก')], default='new', max_length=20)),
                ('payment_method', models.CharField(choices=[('cod', 'เก็บเงินปลายทาง'), ('transfer', 'โอนเงิน')], default='cod', max_length=10)),
                ('address', models.TextField(verbose_name='ที่อยู่จัดส่ง')),
                ('address_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('queue_pos', models.PositiveIntegerField(blank=True, null=True, verbose_name='คิวที่')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.profile')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='accounts.profile')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliveryround')),
            ],
            options={
                'verbose_name': 'คำสั่งซื้อ',
                'verbose_name_plural': 'คำสั่งซื้อ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
        ),
    ]
